image: Ubuntu  # образ для сборки

stack: jdk 22  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

build_script:
  - mvn clean test

#https://www.appveyor.com/docs/appveyor-yml/
#root
