image: Ubuntu  # Используем Ubuntu для сборки

stack: openjdk22  # Версия JDK

environment:
  JAVA_OPTS: "--add-opens java.base/java.lang=ALL-UNNAMED"  # Разрешаем доступ к защищённым методам

init:
  - set APPVEYOR_BUILD_VERBOSE=true  # Включаем подробную отладку

build: false  # Отключаем автоматическое выполнение сборки

build_script:
  - mvn clean test  # Выполняем тесты
  - mvn jacoco:report  # Генерируем отчёт Jacoco

test_script:
  - echo "Tests completed successfully."  # Подтверждаем успешное завершение тестов

on_finish:
  - echo "Build finished."  # Сообщение о завершении сборки
